services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-auth_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/app
    environment:
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-auth_db}
      OAUTH_SERVICE_REDIRECT_URI: ${OAUTH_SERVICE_REDIRECT_URI}
      OAUTH_SERVICE_CLIENT_ID: ${OAUTH_SERVICE_CLIENT_ID}
      OAUTH_SERVICE_CLIENT_SECRET: ${OAUTH_SERVICE_CLIENT_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${REFRESH_TOKEN_EXPIRE_MINUTES:-43200}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "while ! pg_isready -h db -U postgres; do sleep 2; done &&
             cd /app &&
             alembic upgrade head &&
             cd .. &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: